// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mainchain/wrkchain/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3eb2b58804705e6, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method
type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3eb2b58804705e6, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryWrkChainRequest struct {
	WrkchainId uint64 `protobuf:"varint,1,opt,name=wrkchain_id,json=wrkchainId,proto3" json:"wrkchain_id,omitempty"`
}

func (m *QueryWrkChainRequest) Reset()         { *m = QueryWrkChainRequest{} }
func (m *QueryWrkChainRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWrkChainRequest) ProtoMessage()    {}
func (*QueryWrkChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3eb2b58804705e6, []int{2}
}
func (m *QueryWrkChainRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWrkChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWrkChainRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWrkChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWrkChainRequest.Merge(m, src)
}
func (m *QueryWrkChainRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryWrkChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWrkChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWrkChainRequest proto.InternalMessageInfo

func (m *QueryWrkChainRequest) GetWrkchainId() uint64 {
	if m != nil {
		return m.WrkchainId
	}
	return 0
}

type QueryWrkChainResponse struct {
	Wrkchain *WrkChain `protobuf:"bytes,1,opt,name=wrkchain,proto3" json:"wrkchain,omitempty"`
}

func (m *QueryWrkChainResponse) Reset()         { *m = QueryWrkChainResponse{} }
func (m *QueryWrkChainResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWrkChainResponse) ProtoMessage()    {}
func (*QueryWrkChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3eb2b58804705e6, []int{3}
}
func (m *QueryWrkChainResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWrkChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWrkChainResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWrkChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWrkChainResponse.Merge(m, src)
}
func (m *QueryWrkChainResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryWrkChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWrkChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWrkChainResponse proto.InternalMessageInfo

func (m *QueryWrkChainResponse) GetWrkchain() *WrkChain {
	if m != nil {
		return m.Wrkchain
	}
	return nil
}

type QueryWrkChainBlockRequest struct {
	WrkchainId uint64 `protobuf:"varint,1,opt,name=wrkchain_id,json=wrkchainId,proto3" json:"wrkchain_id,omitempty"`
	Height     uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *QueryWrkChainBlockRequest) Reset()         { *m = QueryWrkChainBlockRequest{} }
func (m *QueryWrkChainBlockRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWrkChainBlockRequest) ProtoMessage()    {}
func (*QueryWrkChainBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3eb2b58804705e6, []int{4}
}
func (m *QueryWrkChainBlockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWrkChainBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWrkChainBlockRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWrkChainBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWrkChainBlockRequest.Merge(m, src)
}
func (m *QueryWrkChainBlockRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryWrkChainBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWrkChainBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWrkChainBlockRequest proto.InternalMessageInfo

func (m *QueryWrkChainBlockRequest) GetWrkchainId() uint64 {
	if m != nil {
		return m.WrkchainId
	}
	return 0
}

func (m *QueryWrkChainBlockRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type QueryWrkChainBlockResponse struct {
	Block *WrkChainBlock `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
}

func (m *QueryWrkChainBlockResponse) Reset()         { *m = QueryWrkChainBlockResponse{} }
func (m *QueryWrkChainBlockResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWrkChainBlockResponse) ProtoMessage()    {}
func (*QueryWrkChainBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3eb2b58804705e6, []int{5}
}
func (m *QueryWrkChainBlockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWrkChainBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWrkChainBlockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWrkChainBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWrkChainBlockResponse.Merge(m, src)
}
func (m *QueryWrkChainBlockResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryWrkChainBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWrkChainBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWrkChainBlockResponse proto.InternalMessageInfo

func (m *QueryWrkChainBlockResponse) GetBlock() *WrkChainBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

type QueryWrkChainsFilteredRequest struct {
	Moniker    string             `protobuf:"bytes,1,opt,name=moniker,proto3" json:"moniker,omitempty"`
	Owner      string             `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryWrkChainsFilteredRequest) Reset()         { *m = QueryWrkChainsFilteredRequest{} }
func (m *QueryWrkChainsFilteredRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWrkChainsFilteredRequest) ProtoMessage()    {}
func (*QueryWrkChainsFilteredRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3eb2b58804705e6, []int{6}
}
func (m *QueryWrkChainsFilteredRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWrkChainsFilteredRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWrkChainsFilteredRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWrkChainsFilteredRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWrkChainsFilteredRequest.Merge(m, src)
}
func (m *QueryWrkChainsFilteredRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryWrkChainsFilteredRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWrkChainsFilteredRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWrkChainsFilteredRequest proto.InternalMessageInfo

type QueryWrkChainsFilteredResponse struct {
	Wrkchains  []WrkChain          `protobuf:"bytes,1,rep,name=wrkchains,proto3" json:"wrkchains"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryWrkChainsFilteredResponse) Reset()         { *m = QueryWrkChainsFilteredResponse{} }
func (m *QueryWrkChainsFilteredResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWrkChainsFilteredResponse) ProtoMessage()    {}
func (*QueryWrkChainsFilteredResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3eb2b58804705e6, []int{7}
}
func (m *QueryWrkChainsFilteredResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWrkChainsFilteredResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWrkChainsFilteredResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWrkChainsFilteredResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWrkChainsFilteredResponse.Merge(m, src)
}
func (m *QueryWrkChainsFilteredResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryWrkChainsFilteredResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWrkChainsFilteredResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWrkChainsFilteredResponse proto.InternalMessageInfo

func (m *QueryWrkChainsFilteredResponse) GetWrkchains() []WrkChain {
	if m != nil {
		return m.Wrkchains
	}
	return nil
}

func (m *QueryWrkChainsFilteredResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "mainchain.wrkchain.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "mainchain.wrkchain.v1.QueryParamsResponse")
	proto.RegisterType((*QueryWrkChainRequest)(nil), "mainchain.wrkchain.v1.QueryWrkChainRequest")
	proto.RegisterType((*QueryWrkChainResponse)(nil), "mainchain.wrkchain.v1.QueryWrkChainResponse")
	proto.RegisterType((*QueryWrkChainBlockRequest)(nil), "mainchain.wrkchain.v1.QueryWrkChainBlockRequest")
	proto.RegisterType((*QueryWrkChainBlockResponse)(nil), "mainchain.wrkchain.v1.QueryWrkChainBlockResponse")
	proto.RegisterType((*QueryWrkChainsFilteredRequest)(nil), "mainchain.wrkchain.v1.QueryWrkChainsFilteredRequest")
	proto.RegisterType((*QueryWrkChainsFilteredResponse)(nil), "mainchain.wrkchain.v1.QueryWrkChainsFilteredResponse")
}

func init() { proto.RegisterFile("mainchain/wrkchain/v1/query.proto", fileDescriptor_f3eb2b58804705e6) }

var fileDescriptor_f3eb2b58804705e6 = []byte{
	// 651 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x4f, 0x4f, 0xd4, 0x40,
	0x18, 0xc6, 0x5b, 0x60, 0x57, 0x78, 0x89, 0x07, 0xc7, 0xc5, 0xac, 0x8d, 0xb4, 0xd8, 0xa0, 0xe2,
	0x1f, 0x3a, 0x2e, 0x4a, 0x4c, 0xd0, 0x78, 0x00, 0x83, 0xf1, 0x24, 0x36, 0x24, 0x1a, 0x2f, 0xa4,
	0xbb, 0x3b, 0x76, 0x27, 0xcb, 0x76, 0x4a, 0xa7, 0x0b, 0x12, 0xc2, 0xc5, 0x83, 0xf1, 0x68, 0xe2,
	0xc9, 0xc4, 0x03, 0x5e, 0x3d, 0xf8, 0x01, 0xfc, 0x04, 0x1c, 0x49, 0xbc, 0x78, 0x32, 0x06, 0x3c,
	0xf8, 0x31, 0x4c, 0x67, 0xa6, 0xfb, 0x07, 0x16, 0xb6, 0x7b, 0xeb, 0x4c, 0xdf, 0xe7, 0x79, 0x7f,
	0xef, 0xee, 0xf3, 0x16, 0xae, 0x36, 0x3c, 0x1a, 0x54, 0x6a, 0x1e, 0x0d, 0xf0, 0x56, 0x54, 0x97,
	0x0f, 0x9b, 0x25, 0xbc, 0xd1, 0x24, 0xd1, 0xb6, 0x13, 0x46, 0x2c, 0x66, 0x68, 0xa2, 0x55, 0xe2,
	0xa4, 0x25, 0xce, 0x66, 0xc9, 0x28, 0xf8, 0xcc, 0x67, 0xa2, 0x02, 0x27, 0x4f, 0xb2, 0xd8, 0xb8,
	0xe2, 0x33, 0xe6, 0xaf, 0x13, 0xec, 0x85, 0x14, 0x7b, 0x41, 0xc0, 0x62, 0x2f, 0xa6, 0x2c, 0xe0,
	0xea, 0xad, 0x53, 0x61, 0xbc, 0xc1, 0xf8, 0x1a, 0xaf, 0xd6, 0x71, 0xd9, 0xe3, 0x44, 0xf6, 0xc1,
	0x9b, 0xa5, 0x32, 0x89, 0xbd, 0x12, 0x0e, 0x3d, 0x9f, 0x06, 0x42, 0xa0, 0xea, 0xa7, 0x7b, 0xd3,
	0xb5, 0x30, 0x44, 0x95, 0x5d, 0x00, 0xf4, 0x22, 0xf1, 0x59, 0xf1, 0x22, 0xaf, 0xc1, 0x5d, 0xb2,
	0xd1, 0x24, 0x3c, 0xb6, 0x5d, 0xb8, 0xd8, 0x75, 0xcb, 0x43, 0x16, 0x70, 0x82, 0x1e, 0x42, 0x3e,
	0x14, 0x37, 0x45, 0x7d, 0x4a, 0x9f, 0x19, 0x9f, 0x9b, 0x74, 0x7a, 0x8e, 0xe7, 0x48, 0xd9, 0xe2,
	0xc8, 0xfe, 0x6f, 0x4b, 0x73, 0x95, 0xc4, 0x7e, 0x00, 0x05, 0xe1, 0xf9, 0x32, 0xaa, 0x2f, 0x25,
	0x85, 0xaa, 0x17, 0xb2, 0x60, 0x3c, 0xd5, 0xae, 0xd1, 0xaa, 0x70, 0x1e, 0x71, 0x21, 0xbd, 0x7a,
	0x56, 0xb5, 0x57, 0x61, 0xe2, 0x98, 0xb0, 0x85, 0x33, 0x9a, 0x96, 0x29, 0x20, 0xeb, 0x14, 0xa0,
	0x96, 0xb4, 0x25, 0xb0, 0x57, 0xe1, 0x72, 0x97, 0xeb, 0xe2, 0x3a, 0xab, 0xd4, 0xb3, 0x32, 0xa1,
	0x4b, 0x90, 0xaf, 0x11, 0xea, 0xd7, 0xe2, 0xe2, 0x90, 0x78, 0xa7, 0x4e, 0xf6, 0x2b, 0x30, 0x7a,
	0xb9, 0x2a, 0xe0, 0x05, 0xc8, 0x95, 0x93, 0x0b, 0x45, 0x3b, 0xdd, 0x87, 0x56, 0x8a, 0xa5, 0xc4,
	0xfe, 0xaa, 0xc3, 0x64, 0x97, 0x35, 0x5f, 0xa6, 0xeb, 0x31, 0x89, 0x48, 0x35, 0x85, 0x2e, 0xc2,
	0xb9, 0x06, 0x0b, 0x68, 0x9d, 0x44, 0xc2, 0x7f, 0xcc, 0x4d, 0x8f, 0xa8, 0x00, 0x39, 0xb6, 0x15,
	0x90, 0x48, 0xc0, 0x8e, 0xb9, 0xf2, 0x80, 0x96, 0x01, 0xda, 0xa1, 0x29, 0x0e, 0x0b, 0xa4, 0xeb,
	0x2a, 0x65, 0x4e, 0x92, 0x30, 0x47, 0x26, 0x59, 0x25, 0xcc, 0x59, 0xf1, 0x7c, 0xa2, 0x7a, 0xb9,
	0x1d, 0xca, 0x85, 0xd1, 0x0f, 0x7b, 0x96, 0xf6, 0x6f, 0xcf, 0xd2, 0xec, 0xef, 0x3a, 0x98, 0xa7,
	0x31, 0xaa, 0x9f, 0x60, 0x09, 0xc6, 0xd2, 0x51, 0x93, 0x14, 0x0d, 0x67, 0xf8, 0xd3, 0x54, 0x8e,
	0xda, 0x3a, 0xf4, 0xb4, 0x8b, 0x7c, 0x48, 0x90, 0xdf, 0xe8, 0x4b, 0x2e, 0x09, 0x3a, 0xd1, 0xe7,
	0x3e, 0xe7, 0x20, 0x27, 0x80, 0xd1, 0x7b, 0x1d, 0xf2, 0x32, 0xb6, 0xe8, 0xe6, 0x29, 0x3c, 0x27,
	0xf7, 0xc4, 0xb8, 0x95, 0xa5, 0x54, 0xf6, 0xb5, 0xaf, 0xbd, 0xfb, 0xf9, 0xf7, 0xd3, 0x90, 0x85,
	0x26, 0x71, 0xef, 0xc5, 0x94, 0x6b, 0x82, 0xbe, 0xe8, 0x30, 0x9a, 0x4e, 0x8e, 0x6e, 0x9f, 0xe5,
	0x7f, 0x6c, 0x91, 0x8c, 0x3b, 0xd9, 0x8a, 0x15, 0xce, 0xbc, 0xc0, 0xc1, 0x68, 0x16, 0x9f, 0xfd,
	0x9d, 0xc0, 0x3b, 0x1d, 0x9b, 0xb0, 0x8b, 0x7e, 0xe8, 0x70, 0xbe, 0x2b, 0x9f, 0xe8, 0x6e, 0x96,
	0xb6, 0x9d, 0xdb, 0x65, 0x94, 0x06, 0x50, 0x28, 0xda, 0x27, 0x82, 0xf6, 0x31, 0x7a, 0x34, 0x10,
	0x2d, 0x16, 0xab, 0x83, 0x77, 0xe4, 0x72, 0xee, 0xa2, 0x6f, 0x3a, 0x5c, 0x38, 0x11, 0x4d, 0x74,
	0x3f, 0x0b, 0xce, 0xf1, 0x6d, 0x33, 0xe6, 0x07, 0x54, 0xa9, 0x41, 0x66, 0xc4, 0x20, 0x36, 0x9a,
	0xea, 0x33, 0x08, 0x5f, 0x7c, 0xbe, 0x7f, 0x68, 0xea, 0x07, 0x87, 0xa6, 0xfe, 0xe7, 0xd0, 0xd4,
	0x3f, 0x1e, 0x99, 0xda, 0xc1, 0x91, 0xa9, 0xfd, 0x3a, 0x32, 0xb5, 0xd7, 0xf3, 0x3e, 0x8d, 0x6b,
	0xcd, 0xb2, 0x53, 0x61, 0x0d, 0xdc, 0x0c, 0xe8, 0x1b, 0x5a, 0x11, 0x69, 0x9e, 0x4d, 0xce, 0x6d,
	0xd7, 0xb7, 0x6d, 0xdf, 0x78, 0x3b, 0x24, 0xbc, 0x9c, 0x17, 0x5f, 0xfc, 0x7b, 0xff, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xb1, 0x49, 0x1e, 0x82, 0xb7, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	WrkChain(ctx context.Context, in *QueryWrkChainRequest, opts ...grpc.CallOption) (*QueryWrkChainResponse, error)
	WrkChainBlock(ctx context.Context, in *QueryWrkChainBlockRequest, opts ...grpc.CallOption) (*QueryWrkChainBlockResponse, error)
	WrkChainsFiltered(ctx context.Context, in *QueryWrkChainsFilteredRequest, opts ...grpc.CallOption) (*QueryWrkChainsFilteredResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/mainchain.wrkchain.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) WrkChain(ctx context.Context, in *QueryWrkChainRequest, opts ...grpc.CallOption) (*QueryWrkChainResponse, error) {
	out := new(QueryWrkChainResponse)
	err := c.cc.Invoke(ctx, "/mainchain.wrkchain.v1.Query/WrkChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) WrkChainBlock(ctx context.Context, in *QueryWrkChainBlockRequest, opts ...grpc.CallOption) (*QueryWrkChainBlockResponse, error) {
	out := new(QueryWrkChainBlockResponse)
	err := c.cc.Invoke(ctx, "/mainchain.wrkchain.v1.Query/WrkChainBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) WrkChainsFiltered(ctx context.Context, in *QueryWrkChainsFilteredRequest, opts ...grpc.CallOption) (*QueryWrkChainsFilteredResponse, error) {
	out := new(QueryWrkChainsFilteredResponse)
	err := c.cc.Invoke(ctx, "/mainchain.wrkchain.v1.Query/WrkChainsFiltered", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	WrkChain(context.Context, *QueryWrkChainRequest) (*QueryWrkChainResponse, error)
	WrkChainBlock(context.Context, *QueryWrkChainBlockRequest) (*QueryWrkChainBlockResponse, error)
	WrkChainsFiltered(context.Context, *QueryWrkChainsFilteredRequest) (*QueryWrkChainsFilteredResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) WrkChain(ctx context.Context, req *QueryWrkChainRequest) (*QueryWrkChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WrkChain not implemented")
}
func (*UnimplementedQueryServer) WrkChainBlock(ctx context.Context, req *QueryWrkChainBlockRequest) (*QueryWrkChainBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WrkChainBlock not implemented")
}
func (*UnimplementedQueryServer) WrkChainsFiltered(ctx context.Context, req *QueryWrkChainsFilteredRequest) (*QueryWrkChainsFilteredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WrkChainsFiltered not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mainchain.wrkchain.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_WrkChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWrkChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).WrkChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mainchain.wrkchain.v1.Query/WrkChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).WrkChain(ctx, req.(*QueryWrkChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_WrkChainBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWrkChainBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).WrkChainBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mainchain.wrkchain.v1.Query/WrkChainBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).WrkChainBlock(ctx, req.(*QueryWrkChainBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_WrkChainsFiltered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWrkChainsFilteredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).WrkChainsFiltered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mainchain.wrkchain.v1.Query/WrkChainsFiltered",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).WrkChainsFiltered(ctx, req.(*QueryWrkChainsFilteredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mainchain.wrkchain.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "WrkChain",
			Handler:    _Query_WrkChain_Handler,
		},
		{
			MethodName: "WrkChainBlock",
			Handler:    _Query_WrkChainBlock_Handler,
		},
		{
			MethodName: "WrkChainsFiltered",
			Handler:    _Query_WrkChainsFiltered_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mainchain/wrkchain/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryWrkChainRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWrkChainRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWrkChainRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WrkchainId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.WrkchainId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryWrkChainResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWrkChainResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWrkChainResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Wrkchain != nil {
		{
			size, err := m.Wrkchain.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryWrkChainBlockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWrkChainBlockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWrkChainBlockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if m.WrkchainId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.WrkchainId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryWrkChainBlockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWrkChainBlockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWrkChainBlockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Block != nil {
		{
			size, err := m.Block.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryWrkChainsFilteredRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWrkChainsFilteredRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWrkChainsFilteredRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Moniker) > 0 {
		i -= len(m.Moniker)
		copy(dAtA[i:], m.Moniker)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Moniker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryWrkChainsFilteredResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWrkChainsFilteredResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWrkChainsFilteredResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Wrkchains) > 0 {
		for iNdEx := len(m.Wrkchains) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Wrkchains[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryWrkChainRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WrkchainId != 0 {
		n += 1 + sovQuery(uint64(m.WrkchainId))
	}
	return n
}

func (m *QueryWrkChainResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Wrkchain != nil {
		l = m.Wrkchain.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryWrkChainBlockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WrkchainId != 0 {
		n += 1 + sovQuery(uint64(m.WrkchainId))
	}
	if m.Height != 0 {
		n += 1 + sovQuery(uint64(m.Height))
	}
	return n
}

func (m *QueryWrkChainBlockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Block != nil {
		l = m.Block.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryWrkChainsFilteredRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Moniker)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryWrkChainsFilteredResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Wrkchains) > 0 {
		for _, e := range m.Wrkchains {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWrkChainRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWrkChainRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWrkChainRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WrkchainId", wireType)
			}
			m.WrkchainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WrkchainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWrkChainResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWrkChainResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWrkChainResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wrkchain", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Wrkchain == nil {
				m.Wrkchain = &WrkChain{}
			}
			if err := m.Wrkchain.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWrkChainBlockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWrkChainBlockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWrkChainBlockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WrkchainId", wireType)
			}
			m.WrkchainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WrkchainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWrkChainBlockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWrkChainBlockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWrkChainBlockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Block == nil {
				m.Block = &WrkChainBlock{}
			}
			if err := m.Block.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWrkChainsFilteredRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWrkChainsFilteredRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWrkChainsFilteredRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moniker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Moniker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWrkChainsFilteredResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWrkChainsFilteredResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWrkChainsFilteredResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wrkchains", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Wrkchains = append(m.Wrkchains, WrkChain{})
			if err := m.Wrkchains[len(m.Wrkchains)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
