// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mainchain/wrkchain/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterWrkChain struct {
	Moniker     string `protobuf:"bytes,2,opt,name=moniker,proto3" json:"moniker,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	GenesisHash string `protobuf:"bytes,4,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis" yaml:"genesis"`
	BaseType    string `protobuf:"bytes,5,opt,name=base_type,json=baseType,proto3" json:"type" yaml:"type"`
	Owner       string `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *MsgRegisterWrkChain) Reset()         { *m = MsgRegisterWrkChain{} }
func (m *MsgRegisterWrkChain) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterWrkChain) ProtoMessage()    {}
func (*MsgRegisterWrkChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_631f41fcf7533fdf, []int{0}
}
func (m *MsgRegisterWrkChain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterWrkChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterWrkChain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterWrkChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterWrkChain.Merge(m, src)
}
func (m *MsgRegisterWrkChain) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterWrkChain) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterWrkChain.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterWrkChain proto.InternalMessageInfo

// MsgRegisterBeaconResponse defines the Msg/RegisterBeacon response type.
type MsgRegisterWrkChainResponse struct {
	WrkchainId uint64 `protobuf:"varint,1,opt,name=wrkchain_id,json=wrkchainId,proto3" json:"wrkchain_id,omitempty"`
}

func (m *MsgRegisterWrkChainResponse) Reset()         { *m = MsgRegisterWrkChainResponse{} }
func (m *MsgRegisterWrkChainResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterWrkChainResponse) ProtoMessage()    {}
func (*MsgRegisterWrkChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_631f41fcf7533fdf, []int{1}
}
func (m *MsgRegisterWrkChainResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterWrkChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterWrkChainResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterWrkChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterWrkChainResponse.Merge(m, src)
}
func (m *MsgRegisterWrkChainResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterWrkChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterWrkChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterWrkChainResponse proto.InternalMessageInfo

func (m *MsgRegisterWrkChainResponse) GetWrkchainId() uint64 {
	if m != nil {
		return m.WrkchainId
	}
	return 0
}

type MsgRecordWrkChainBlock struct {
	WrkchainId uint64 `protobuf:"varint,1,opt,name=wrkchain_id,json=wrkchainId,proto3" json:"wrkchain_id,omitempty"`
	Height     uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	BlockHash  string `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"blockhash" yaml:"blockhash"`
	ParentHash string `protobuf:"bytes,4,opt,name=parent_hash,json=parentHash,proto3" json:"parenthash" yaml:"parenthash"`
	Hash1      string `protobuf:"bytes,5,opt,name=hash1,proto3" json:"hash1,omitempty"`
	Hash2      string `protobuf:"bytes,6,opt,name=hash2,proto3" json:"hash2,omitempty"`
	Hash3      string `protobuf:"bytes,7,opt,name=hash3,proto3" json:"hash3,omitempty"`
	Owner      string `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *MsgRecordWrkChainBlock) Reset()         { *m = MsgRecordWrkChainBlock{} }
func (m *MsgRecordWrkChainBlock) String() string { return proto.CompactTextString(m) }
func (*MsgRecordWrkChainBlock) ProtoMessage()    {}
func (*MsgRecordWrkChainBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_631f41fcf7533fdf, []int{2}
}
func (m *MsgRecordWrkChainBlock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRecordWrkChainBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRecordWrkChainBlock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRecordWrkChainBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRecordWrkChainBlock.Merge(m, src)
}
func (m *MsgRecordWrkChainBlock) XXX_Size() int {
	return m.Size()
}
func (m *MsgRecordWrkChainBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRecordWrkChainBlock.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRecordWrkChainBlock proto.InternalMessageInfo

type MsgRecordWrkChainBlockResponse struct {
	WrkchainId uint64 `protobuf:"varint,1,opt,name=wrkchain_id,json=wrkchainId,proto3" json:"wrkchain_id,omitempty"`
	Height     uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *MsgRecordWrkChainBlockResponse) Reset()         { *m = MsgRecordWrkChainBlockResponse{} }
func (m *MsgRecordWrkChainBlockResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRecordWrkChainBlockResponse) ProtoMessage()    {}
func (*MsgRecordWrkChainBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_631f41fcf7533fdf, []int{3}
}
func (m *MsgRecordWrkChainBlockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRecordWrkChainBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRecordWrkChainBlockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRecordWrkChainBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRecordWrkChainBlockResponse.Merge(m, src)
}
func (m *MsgRecordWrkChainBlockResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRecordWrkChainBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRecordWrkChainBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRecordWrkChainBlockResponse proto.InternalMessageInfo

func (m *MsgRecordWrkChainBlockResponse) GetWrkchainId() uint64 {
	if m != nil {
		return m.WrkchainId
	}
	return 0
}

func (m *MsgRecordWrkChainBlockResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgRegisterWrkChain)(nil), "mainchain.beacon.v1.MsgRegisterWrkChain")
	proto.RegisterType((*MsgRegisterWrkChainResponse)(nil), "mainchain.beacon.v1.MsgRegisterWrkChainResponse")
	proto.RegisterType((*MsgRecordWrkChainBlock)(nil), "mainchain.beacon.v1.MsgRecordWrkChainBlock")
	proto.RegisterType((*MsgRecordWrkChainBlockResponse)(nil), "mainchain.beacon.v1.MsgRecordWrkChainBlockResponse")
}

func init() { proto.RegisterFile("mainchain/wrkchain/v1/tx.proto", fileDescriptor_631f41fcf7533fdf) }

var fileDescriptor_631f41fcf7533fdf = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcf, 0x6e, 0xd3, 0x30,
	0x1c, 0x6e, 0xb6, 0xae, 0x7f, 0x7e, 0x45, 0x68, 0xb8, 0xd5, 0x88, 0x8a, 0x48, 0x46, 0xe0, 0x50,
	0x09, 0x91, 0xd2, 0x15, 0x2e, 0x3b, 0xa0, 0xa9, 0x70, 0x80, 0xc3, 0x84, 0x14, 0x21, 0x21, 0xb8,
	0x54, 0x6e, 0x6a, 0x12, 0xab, 0xab, 0x5d, 0xc5, 0xd9, 0xba, 0xbe, 0x01, 0x47, 0x1e, 0x61, 0xef,
	0xc1, 0x0b, 0x70, 0xdc, 0x11, 0x09, 0x29, 0x42, 0xed, 0x05, 0xf5, 0xc0, 0xa1, 0x4f, 0x80, 0x6c,
	0x27, 0x2d, 0xd2, 0x32, 0x31, 0x6e, 0xbf, 0xef, 0xfb, 0x7d, 0xbf, 0x2f, 0xf6, 0x17, 0xdb, 0x60,
	0x8d, 0x31, 0x65, 0x7e, 0x88, 0x29, 0x6b, 0x4f, 0xa3, 0x91, 0x2e, 0xce, 0x3a, 0xed, 0xf8, 0xdc,
	0x9d, 0x44, 0x3c, 0xe6, 0xa8, 0xbe, 0xee, 0xbb, 0x03, 0x82, 0x7d, 0xce, 0xdc, 0xb3, 0x4e, 0xb3,
	0x11, 0xf0, 0x80, 0xab, 0x7e, 0x5b, 0x56, 0x5a, 0xda, 0x7c, 0x94, 0x6f, 0x95, 0xd5, 0x5a, 0xe5,
	0xfc, 0x30, 0xa0, 0x7e, 0x2c, 0x02, 0x8f, 0x04, 0x54, 0xc4, 0x24, 0x7a, 0x1f, 0x8d, 0x5e, 0xca,
	0x2e, 0x32, 0xa1, 0x3c, 0xe6, 0x8c, 0x8e, 0x48, 0x64, 0x6e, 0xed, 0x1b, 0xad, 0xaa, 0x97, 0x41,
	0x84, 0xa0, 0xc8, 0xf0, 0x98, 0x98, 0xdb, 0x8a, 0x56, 0x35, 0x3a, 0x82, 0x5b, 0x01, 0x61, 0x44,
	0x50, 0xd1, 0x0f, 0xb1, 0x08, 0xcd, 0xa2, 0xec, 0xf5, 0xee, 0x2f, 0x13, 0xbb, 0x9c, 0xf2, 0xab,
	0xc4, 0xbe, 0x3d, 0xc3, 0xe3, 0x93, 0x43, 0x27, 0x25, 0x1c, 0xaf, 0x96, 0x56, 0xaf, 0xb1, 0x08,
	0xd1, 0x33, 0xa8, 0x0e, 0xb0, 0x20, 0xfd, 0x78, 0x36, 0x21, 0xe6, 0x8e, 0x1a, 0xbf, 0xbb, 0x4c,
	0xec, 0xa2, 0xc4, 0xab, 0xc4, 0xae, 0xe9, 0x59, 0x89, 0x1c, 0xaf, 0x22, 0x95, 0xef, 0x66, 0x13,
	0x82, 0x1a, 0xb0, 0xc3, 0xa7, 0x8c, 0x44, 0x66, 0x49, 0x2d, 0x46, 0x83, 0xc3, 0xca, 0xe7, 0x0b,
	0xbb, 0xf0, 0xeb, 0xc2, 0x2e, 0x38, 0x2f, 0xe0, 0x5e, 0xce, 0xe6, 0x3c, 0x22, 0x26, 0x9c, 0x09,
	0x82, 0x6c, 0xa8, 0x65, 0x71, 0xf4, 0xe9, 0xd0, 0x34, 0xf6, 0x8d, 0x56, 0xd1, 0x83, 0x8c, 0x7a,
	0x33, 0x74, 0xbe, 0x6e, 0xc1, 0x9e, 0x32, 0xf0, 0x79, 0x34, 0xcc, 0xc6, 0x7b, 0x27, 0xdc, 0x1f,
	0xfd, 0x73, 0x16, 0xed, 0x41, 0x29, 0x24, 0x34, 0x08, 0x63, 0x15, 0x60, 0xd1, 0x4b, 0x11, 0x3a,
	0x02, 0x18, 0x48, 0x07, 0x9d, 0x94, 0x4a, 0xb1, 0xf7, 0x60, 0x99, 0xd8, 0x55, 0xc5, 0x4a, 0x72,
	0x95, 0xd8, 0xbb, 0x7a, 0xbf, 0x6b, 0xca, 0xf1, 0x74, 0x5b, 0x65, 0xf5, 0x0a, 0x6a, 0x13, 0x1c,
	0x11, 0x16, 0xff, 0x1d, 0xf6, 0xc3, 0x65, 0x62, 0x83, 0xa6, 0x53, 0x8f, 0x3b, 0xda, 0x63, 0xc3,
	0x39, 0x5e, 0x2a, 0x50, 0x2e, 0x0d, 0xd8, 0x91, 0x64, 0x47, 0xa7, 0xed, 0x69, 0x90, 0xb1, 0x07,
	0x59, 0xa2, 0x0a, 0x64, 0x6c, 0xd7, 0x2c, 0x6f, 0xd8, 0xee, 0x26, 0xfd, 0x4a, 0x7e, 0xfa, 0x1f,
	0xc0, 0xca, 0x0f, 0xef, 0xc6, 0x3f, 0xe0, 0xba, 0x10, 0x0f, 0x7e, 0x1b, 0xb0, 0x7d, 0x2c, 0x02,
	0xc4, 0x60, 0xf7, 0xca, 0xd1, 0x6d, 0xb9, 0x39, 0x97, 0xc4, 0xcd, 0x39, 0x07, 0xcd, 0xa7, 0x37,
	0x55, 0xae, 0x17, 0x3c, 0x85, 0x7a, 0xde, 0x61, 0x78, 0x7c, 0xbd, 0xd1, 0x15, 0x71, 0xb3, 0xfb,
	0x1f, 0xe2, 0xec, 0xc3, 0xbd, 0xb7, 0xdf, 0xe6, 0x96, 0x71, 0x39, 0xb7, 0x8c, 0x9f, 0x73, 0xcb,
	0xf8, 0xb2, 0xb0, 0x0a, 0x97, 0x0b, 0xab, 0xf0, 0x7d, 0x61, 0x15, 0x3e, 0x3e, 0x0f, 0x68, 0x1c,
	0x9e, 0x0e, 0x5c, 0x9f, 0x8f, 0xdb, 0xa7, 0x8c, 0x7e, 0xa2, 0x3e, 0x8e, 0x29, 0x67, 0x4f, 0x24,
	0xde, 0x3c, 0x01, 0xe7, 0x9b, 0x47, 0x40, 0x5e, 0x22, 0x31, 0x28, 0xa9, 0xfb, 0xdf, 0xfd, 0x13,
	0x00, 0x00, 0xff, 0xff, 0x3a, 0x82, 0x88, 0xdc, 0x72, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UndPurchaseOrder defines a method to create new purchase order.
	RegisterWrkChain(ctx context.Context, in *MsgRegisterWrkChain, opts ...grpc.CallOption) (*MsgRegisterWrkChainResponse, error)
	RecordWrkChainBlock(ctx context.Context, in *MsgRecordWrkChainBlock, opts ...grpc.CallOption) (*MsgRecordWrkChainBlockResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterWrkChain(ctx context.Context, in *MsgRegisterWrkChain, opts ...grpc.CallOption) (*MsgRegisterWrkChainResponse, error) {
	out := new(MsgRegisterWrkChainResponse)
	err := c.cc.Invoke(ctx, "/mainchain.beacon.v1.Msg/RegisterWrkChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RecordWrkChainBlock(ctx context.Context, in *MsgRecordWrkChainBlock, opts ...grpc.CallOption) (*MsgRecordWrkChainBlockResponse, error) {
	out := new(MsgRecordWrkChainBlockResponse)
	err := c.cc.Invoke(ctx, "/mainchain.beacon.v1.Msg/RecordWrkChainBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UndPurchaseOrder defines a method to create new purchase order.
	RegisterWrkChain(context.Context, *MsgRegisterWrkChain) (*MsgRegisterWrkChainResponse, error)
	RecordWrkChainBlock(context.Context, *MsgRecordWrkChainBlock) (*MsgRecordWrkChainBlockResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterWrkChain(ctx context.Context, req *MsgRegisterWrkChain) (*MsgRegisterWrkChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWrkChain not implemented")
}
func (*UnimplementedMsgServer) RecordWrkChainBlock(ctx context.Context, req *MsgRecordWrkChainBlock) (*MsgRecordWrkChainBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordWrkChainBlock not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterWrkChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterWrkChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterWrkChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mainchain.beacon.v1.Msg/RegisterWrkChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterWrkChain(ctx, req.(*MsgRegisterWrkChain))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RecordWrkChainBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRecordWrkChainBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RecordWrkChainBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mainchain.beacon.v1.Msg/RecordWrkChainBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RecordWrkChainBlock(ctx, req.(*MsgRecordWrkChainBlock))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mainchain.beacon.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWrkChain",
			Handler:    _Msg_RegisterWrkChain_Handler,
		},
		{
			MethodName: "RecordWrkChainBlock",
			Handler:    _Msg_RecordWrkChainBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mainchain/wrkchain/v1/tx.proto",
}

func (m *MsgRegisterWrkChain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterWrkChain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterWrkChain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.BaseType) > 0 {
		i -= len(m.BaseType)
		copy(dAtA[i:], m.BaseType)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BaseType)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.GenesisHash) > 0 {
		i -= len(m.GenesisHash)
		copy(dAtA[i:], m.GenesisHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GenesisHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Moniker) > 0 {
		i -= len(m.Moniker)
		copy(dAtA[i:], m.Moniker)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Moniker)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterWrkChainResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterWrkChainResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterWrkChainResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WrkchainId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WrkchainId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgRecordWrkChainBlock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRecordWrkChainBlock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRecordWrkChainBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Hash3) > 0 {
		i -= len(m.Hash3)
		copy(dAtA[i:], m.Hash3)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Hash3)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Hash2) > 0 {
		i -= len(m.Hash2)
		copy(dAtA[i:], m.Hash2)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Hash2)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Hash1) > 0 {
		i -= len(m.Hash1)
		copy(dAtA[i:], m.Hash1)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Hash1)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ParentHash) > 0 {
		i -= len(m.ParentHash)
		copy(dAtA[i:], m.ParentHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ParentHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BlockHash) > 0 {
		i -= len(m.BlockHash)
		copy(dAtA[i:], m.BlockHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BlockHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Height != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if m.WrkchainId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WrkchainId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgRecordWrkChainBlockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRecordWrkChainBlockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRecordWrkChainBlockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if m.WrkchainId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WrkchainId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterWrkChain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Moniker)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GenesisHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BaseType)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterWrkChainResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WrkchainId != 0 {
		n += 1 + sovTx(uint64(m.WrkchainId))
	}
	return n
}

func (m *MsgRecordWrkChainBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WrkchainId != 0 {
		n += 1 + sovTx(uint64(m.WrkchainId))
	}
	if m.Height != 0 {
		n += 1 + sovTx(uint64(m.Height))
	}
	l = len(m.BlockHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ParentHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Hash1)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Hash2)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Hash3)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRecordWrkChainBlockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WrkchainId != 0 {
		n += 1 + sovTx(uint64(m.WrkchainId))
	}
	if m.Height != 0 {
		n += 1 + sovTx(uint64(m.Height))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterWrkChain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterWrkChain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterWrkChain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moniker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Moniker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GenesisHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterWrkChainResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterWrkChainResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterWrkChainResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WrkchainId", wireType)
			}
			m.WrkchainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WrkchainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRecordWrkChainBlock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRecordWrkChainBlock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRecordWrkChainBlock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WrkchainId", wireType)
			}
			m.WrkchainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WrkchainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParentHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParentHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash1", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash1 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash2", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash2 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash3", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash3 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRecordWrkChainBlockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRecordWrkChainBlockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRecordWrkChainBlockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WrkchainId", wireType)
			}
			m.WrkchainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WrkchainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
