// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mainchain/beacon/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgRegisterBeacon represents a message to register a new beacon
type MsgRegisterBeacon struct {
	// moniker is a short identifier for a beacon
	Moniker string `protobuf:"bytes,1,opt,name=moniker,proto3" json:"moniker,omitempty"`
	// name is a long name for a beacon
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// owner is the address of the owner of the beacon
	Owner string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *MsgRegisterBeacon) Reset()         { *m = MsgRegisterBeacon{} }
func (m *MsgRegisterBeacon) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterBeacon) ProtoMessage()    {}
func (*MsgRegisterBeacon) Descriptor() ([]byte, []int) {
	return fileDescriptor_e58884c800f582f9, []int{0}
}
func (m *MsgRegisterBeacon) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterBeacon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterBeacon.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterBeacon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterBeacon.Merge(m, src)
}
func (m *MsgRegisterBeacon) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterBeacon) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterBeacon.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterBeacon proto.InternalMessageInfo

// MsgRegisterBeaconResponse defines the Msg/RegisterBeacon response type.
type MsgRegisterBeaconResponse struct {
	// beacon_id is the id of the new beacon
	BeaconId uint64 `protobuf:"varint,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`
}

func (m *MsgRegisterBeaconResponse) Reset()         { *m = MsgRegisterBeaconResponse{} }
func (m *MsgRegisterBeaconResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterBeaconResponse) ProtoMessage()    {}
func (*MsgRegisterBeaconResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e58884c800f582f9, []int{1}
}
func (m *MsgRegisterBeaconResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterBeaconResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterBeaconResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterBeaconResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterBeaconResponse.Merge(m, src)
}
func (m *MsgRegisterBeaconResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterBeaconResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterBeaconResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterBeaconResponse proto.InternalMessageInfo

func (m *MsgRegisterBeaconResponse) GetBeaconId() uint64 {
	if m != nil {
		return m.BeaconId
	}
	return 0
}

// MsgRecordBeaconTimestamp represents a message to record a timestamp for a registered beacon
type MsgRecordBeaconTimestamp struct {
	// beacon_id is the id of the beacon the timestamp is being submitted for
	BeaconId uint64 `protobuf:"varint,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`
	// hash is the hash or data being submitted
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// submit_time is a unix epoch value of the submission time
	SubmitTime uint64 `protobuf:"varint,3,opt,name=submit_time,json=submitTime,proto3" json:"submit_time,omitempty"`
	// owner is the address of the owner of the beacon
	Owner string `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *MsgRecordBeaconTimestamp) Reset()         { *m = MsgRecordBeaconTimestamp{} }
func (m *MsgRecordBeaconTimestamp) String() string { return proto.CompactTextString(m) }
func (*MsgRecordBeaconTimestamp) ProtoMessage()    {}
func (*MsgRecordBeaconTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e58884c800f582f9, []int{2}
}
func (m *MsgRecordBeaconTimestamp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRecordBeaconTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRecordBeaconTimestamp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRecordBeaconTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRecordBeaconTimestamp.Merge(m, src)
}
func (m *MsgRecordBeaconTimestamp) XXX_Size() int {
	return m.Size()
}
func (m *MsgRecordBeaconTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRecordBeaconTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRecordBeaconTimestamp proto.InternalMessageInfo

// MsgRecordBeaconTimestampResponse defines the Msg/RecordBeacon response type.
type MsgRecordBeaconTimestampResponse struct {
	// beacon_id is the id of the beacon
	BeaconId uint64 `protobuf:"varint,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`
	// timestamp_id is the id of the new timestamp
	TimestampId uint64 `protobuf:"varint,2,opt,name=timestamp_id,json=timestampId,proto3" json:"timestamp_id,omitempty"`
}

func (m *MsgRecordBeaconTimestampResponse) Reset()         { *m = MsgRecordBeaconTimestampResponse{} }
func (m *MsgRecordBeaconTimestampResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRecordBeaconTimestampResponse) ProtoMessage()    {}
func (*MsgRecordBeaconTimestampResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e58884c800f582f9, []int{3}
}
func (m *MsgRecordBeaconTimestampResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRecordBeaconTimestampResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRecordBeaconTimestampResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRecordBeaconTimestampResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRecordBeaconTimestampResponse.Merge(m, src)
}
func (m *MsgRecordBeaconTimestampResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRecordBeaconTimestampResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRecordBeaconTimestampResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRecordBeaconTimestampResponse proto.InternalMessageInfo

func (m *MsgRecordBeaconTimestampResponse) GetBeaconId() uint64 {
	if m != nil {
		return m.BeaconId
	}
	return 0
}

func (m *MsgRecordBeaconTimestampResponse) GetTimestampId() uint64 {
	if m != nil {
		return m.TimestampId
	}
	return 0
}

// MsgPurchaseBeaconStateStorage represents a message to purchase more beacon storage
type MsgPurchaseBeaconStateStorage struct {
	// beacon_id is the id of the beacon the storage is being purchased for
	BeaconId uint64 `protobuf:"varint,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`
	// number is the number of state storage spaces to purchase
	Number uint64 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	// owner is the address of the owner of the beacon
	Owner string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *MsgPurchaseBeaconStateStorage) Reset()         { *m = MsgPurchaseBeaconStateStorage{} }
func (m *MsgPurchaseBeaconStateStorage) String() string { return proto.CompactTextString(m) }
func (*MsgPurchaseBeaconStateStorage) ProtoMessage()    {}
func (*MsgPurchaseBeaconStateStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e58884c800f582f9, []int{4}
}
func (m *MsgPurchaseBeaconStateStorage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPurchaseBeaconStateStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPurchaseBeaconStateStorage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPurchaseBeaconStateStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPurchaseBeaconStateStorage.Merge(m, src)
}
func (m *MsgPurchaseBeaconStateStorage) XXX_Size() int {
	return m.Size()
}
func (m *MsgPurchaseBeaconStateStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPurchaseBeaconStateStorage.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPurchaseBeaconStateStorage proto.InternalMessageInfo

// MsgPurchaseBeaconStateStorageResponse defines the Msg/PurchaseBeaconStateStorage response type.
type MsgPurchaseBeaconStateStorageResponse struct {
	// beacon_id is the id of the beacon the storage is being purchased for
	BeaconId uint64 `protobuf:"varint,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`
	// number_purchased is the number of state storage spaces purchased
	NumberPurchased uint64 `protobuf:"varint,2,opt,name=number_purchased,json=numberPurchased,proto3" json:"number_purchased,omitempty"`
	// num_can_purchase is the number of remaining slots available for purchase
	NumCanPurchase uint64 `protobuf:"varint,3,opt,name=num_can_purchase,json=numCanPurchase,proto3" json:"num_can_purchase,omitempty"`
}

func (m *MsgPurchaseBeaconStateStorageResponse) Reset()         { *m = MsgPurchaseBeaconStateStorageResponse{} }
func (m *MsgPurchaseBeaconStateStorageResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPurchaseBeaconStateStorageResponse) ProtoMessage()    {}
func (*MsgPurchaseBeaconStateStorageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e58884c800f582f9, []int{5}
}
func (m *MsgPurchaseBeaconStateStorageResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPurchaseBeaconStateStorageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPurchaseBeaconStateStorageResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPurchaseBeaconStateStorageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPurchaseBeaconStateStorageResponse.Merge(m, src)
}
func (m *MsgPurchaseBeaconStateStorageResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPurchaseBeaconStateStorageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPurchaseBeaconStateStorageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPurchaseBeaconStateStorageResponse proto.InternalMessageInfo

func (m *MsgPurchaseBeaconStateStorageResponse) GetBeaconId() uint64 {
	if m != nil {
		return m.BeaconId
	}
	return 0
}

func (m *MsgPurchaseBeaconStateStorageResponse) GetNumberPurchased() uint64 {
	if m != nil {
		return m.NumberPurchased
	}
	return 0
}

func (m *MsgPurchaseBeaconStateStorageResponse) GetNumCanPurchase() uint64 {
	if m != nil {
		return m.NumCanPurchase
	}
	return 0
}

// MsgUpdateParams is the Msg/UpdateParams request type.
//
// Since: cosmos-sdk 0.47
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the x/beacon parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_e58884c800f582f9, []int{6}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
//
// Since: cosmos-sdk 0.47
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e58884c800f582f9, []int{7}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterBeacon)(nil), "mainchain.beacon.v1.MsgRegisterBeacon")
	proto.RegisterType((*MsgRegisterBeaconResponse)(nil), "mainchain.beacon.v1.MsgRegisterBeaconResponse")
	proto.RegisterType((*MsgRecordBeaconTimestamp)(nil), "mainchain.beacon.v1.MsgRecordBeaconTimestamp")
	proto.RegisterType((*MsgRecordBeaconTimestampResponse)(nil), "mainchain.beacon.v1.MsgRecordBeaconTimestampResponse")
	proto.RegisterType((*MsgPurchaseBeaconStateStorage)(nil), "mainchain.beacon.v1.MsgPurchaseBeaconStateStorage")
	proto.RegisterType((*MsgPurchaseBeaconStateStorageResponse)(nil), "mainchain.beacon.v1.MsgPurchaseBeaconStateStorageResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "mainchain.beacon.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "mainchain.beacon.v1.MsgUpdateParamsResponse")
}

func init() { proto.RegisterFile("mainchain/beacon/v1/tx.proto", fileDescriptor_e58884c800f582f9) }

var fileDescriptor_e58884c800f582f9 = []byte{
	// 702 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xc1, 0x4f, 0xd4, 0x4e,
	0x14, 0xde, 0xc2, 0xc2, 0xef, 0xb7, 0x03, 0x01, 0xa9, 0x28, 0x4b, 0xd1, 0x5d, 0x6c, 0xd0, 0x20,
	0x91, 0x36, 0x40, 0x20, 0x06, 0x13, 0x13, 0xd7, 0x13, 0x87, 0x4d, 0x48, 0xd1, 0x8b, 0x97, 0xcd,
	0xb4, 0x1d, 0xdb, 0x89, 0x99, 0x99, 0xa6, 0x33, 0x45, 0x38, 0x98, 0x18, 0x4f, 0xc6, 0x78, 0xf0,
	0xea, 0x8d, 0x78, 0xf2, 0xc8, 0xc1, 0x3f, 0x40, 0x6f, 0x1c, 0x89, 0xf1, 0xe0, 0xc9, 0x18, 0x38,
	0xc0, 0x9f, 0x61, 0x3a, 0xd3, 0xee, 0x22, 0x74, 0xd7, 0xe5, 0xb2, 0x99, 0xf9, 0xde, 0xf7, 0xde,
	0xfb, 0xe6, 0xdb, 0x37, 0x53, 0x70, 0x83, 0x40, 0x4c, 0xbd, 0x10, 0x62, 0x6a, 0xbb, 0x08, 0x7a,
	0x8c, 0xda, 0xdb, 0x4b, 0xb6, 0xd8, 0xb1, 0xa2, 0x98, 0x09, 0xa6, 0x5f, 0x6d, 0x47, 0x2d, 0x15,
	0xb5, 0xb6, 0x97, 0x8c, 0x29, 0x8f, 0x71, 0xc2, 0xb8, 0x4d, 0x78, 0x90, 0x92, 0x09, 0x0f, 0x14,
	0xdb, 0x98, 0x56, 0x81, 0x96, 0xdc, 0xd9, 0x6a, 0x93, 0x85, 0x26, 0x03, 0x16, 0x30, 0x85, 0xa7,
	0xab, 0x0c, 0x9d, 0x80, 0x04, 0x53, 0x66, 0xcb, 0xdf, 0x0c, 0x9a, 0x2d, 0xd2, 0x93, 0xf5, 0x96,
	0x0c, 0xf3, 0x93, 0x06, 0x26, 0x9a, 0x3c, 0x70, 0x50, 0x80, 0xb9, 0x40, 0x71, 0x43, 0xc6, 0xf4,
	0x2a, 0xf8, 0x8f, 0x30, 0x8a, 0x5f, 0xa0, 0xb8, 0xaa, 0xcd, 0x6a, 0xf3, 0x15, 0x27, 0xdf, 0xea,
	0x3a, 0x28, 0x53, 0x48, 0x50, 0x75, 0x40, 0xc2, 0x72, 0xad, 0x5b, 0x60, 0x88, 0xbd, 0xa4, 0x28,
	0xae, 0x0e, 0xa6, 0x60, 0xa3, 0xfa, 0xfd, 0xcb, 0xe2, 0x64, 0xa6, 0xf7, 0x91, 0xef, 0xc7, 0x88,
	0xf3, 0x2d, 0x11, 0x63, 0x1a, 0x38, 0x8a, 0xb6, 0x6e, 0xbf, 0xdd, 0xab, 0x97, 0x4e, 0xf7, 0xea,
	0xa5, 0x37, 0x27, 0xfb, 0x0b, 0x0a, 0x7b, 0x77, 0xb2, 0xbf, 0x50, 0xcd, 0x24, 0x5e, 0x90, 0x63,
	0xde, 0x07, 0xd3, 0x17, 0x40, 0x07, 0xf1, 0x88, 0x51, 0x8e, 0xf4, 0x19, 0x50, 0x51, 0x89, 0x2d,
	0xec, 0x4b, 0xb5, 0x65, 0xe7, 0x7f, 0x05, 0x6c, 0xf8, 0xe6, 0x0f, 0x0d, 0x54, 0x65, 0xaa, 0xc7,
	0x62, 0x5f, 0x25, 0x3e, 0xc1, 0x04, 0x71, 0x01, 0x49, 0xd4, 0x33, 0x33, 0x3d, 0x68, 0x08, 0x79,
	0x98, 0x1f, 0x34, 0x5d, 0xeb, 0x75, 0x30, 0xc2, 0x13, 0x97, 0x60, 0xd1, 0x12, 0x98, 0x20, 0x79,
	0xdc, 0xb2, 0x03, 0x14, 0x94, 0x96, 0xed, 0x38, 0x51, 0xee, 0xcf, 0x89, 0xb5, 0x62, 0x27, 0xea,
	0x67, 0x9d, 0x28, 0x50, 0x6e, 0xba, 0x60, 0xb6, 0x5b, 0xac, 0x2f, 0x5f, 0xf4, 0x5b, 0x60, 0x54,
	0xe4, 0x19, 0x69, 0x7c, 0x40, 0xc6, 0x47, 0xda, 0xd8, 0x86, 0x6f, 0x7e, 0xd3, 0xc0, 0xcd, 0x26,
	0x0f, 0x36, 0x93, 0xd8, 0x0b, 0x21, 0x47, 0xaa, 0xcd, 0x96, 0x80, 0x02, 0x6d, 0x09, 0x16, 0xc3,
	0xe0, 0x1f, 0x1d, 0xae, 0x83, 0x61, 0x9a, 0x10, 0x17, 0xc5, 0x59, 0xed, 0x6c, 0x77, 0xe9, 0x61,
	0x79, 0x50, 0x6c, 0xd1, 0x5c, 0xc7, 0xa2, 0xee, 0x0a, 0xcd, 0x8f, 0x1a, 0xb8, 0xdd, 0x93, 0xd1,
	0x9f, 0x5b, 0x77, 0xc1, 0x15, 0xa5, 0xbe, 0x15, 0x65, 0x95, 0x72, 0xc7, 0xc6, 0x15, 0x9e, 0x37,
	0xf0, 0xf5, 0x79, 0x49, 0x6d, 0x79, 0x90, 0xb6, 0xb9, 0xd9, 0x9c, 0x8c, 0xd1, 0x84, 0x3c, 0x86,
	0x34, 0xa7, 0x9a, 0x5f, 0x35, 0x30, 0xde, 0xe4, 0xc1, 0xd3, 0xc8, 0x87, 0x02, 0x6d, 0xc2, 0x18,
	0x12, 0xae, 0xaf, 0x81, 0x0a, 0x4c, 0x44, 0xc8, 0x62, 0x2c, 0x76, 0xd5, 0xcd, 0xeb, 0x61, 0x50,
	0x87, 0xaa, 0x3f, 0x04, 0xc3, 0x91, 0xac, 0x20, 0x65, 0x8d, 0x2c, 0xcf, 0x58, 0x05, 0x4f, 0x8d,
	0xa5, 0x9a, 0x34, 0x2a, 0x07, 0xbf, 0xea, 0xa5, 0xcf, 0x27, 0xfb, 0x0b, 0x9a, 0x93, 0x65, 0xad,
	0xaf, 0xa6, 0xe6, 0x76, 0xea, 0xa5, 0x06, 0x9b, 0x9d, 0xa7, 0x63, 0xc7, 0xee, 0x98, 0x7d, 0x56,
	0xae, 0x39, 0x0d, 0xa6, 0xce, 0x41, 0xb9, 0x9f, 0xcb, 0xa7, 0x83, 0x60, 0xb0, 0xc9, 0x03, 0x3d,
	0x04, 0x63, 0xe7, 0xde, 0x96, 0x3b, 0x85, 0xda, 0x2e, 0xdc, 0x6f, 0xc3, 0xea, 0x8f, 0xd7, 0xfe,
	0x07, 0x5f, 0x81, 0x6b, 0xc5, 0xd7, 0x7c, 0xb1, 0x7b, 0xa1, 0x02, 0xba, 0xb1, 0x7a, 0x29, 0x7a,
	0xbb, 0xfd, 0x7b, 0x0d, 0x18, 0x3d, 0xee, 0xca, 0x72, 0xb7, 0xaa, 0xdd, 0x73, 0x8c, 0xf5, 0xcb,
	0xe7, 0xb4, 0xe5, 0xb8, 0x60, 0xf4, 0xaf, 0xc9, 0x9a, 0xeb, 0x56, 0xeb, 0x2c, 0xcb, 0xb8, 0xd7,
	0x0f, 0x2b, 0xef, 0x61, 0x0c, 0xbd, 0x4e, 0x87, 0xa8, 0xd1, 0x3c, 0x38, 0xaa, 0x69, 0x87, 0x47,
	0x35, 0xed, 0xf7, 0x51, 0x4d, 0xfb, 0x70, 0x5c, 0x2b, 0x1d, 0x1e, 0xd7, 0x4a, 0x3f, 0x8f, 0x6b,
	0xa5, 0x67, 0x2b, 0x01, 0x16, 0x61, 0xe2, 0x5a, 0x1e, 0x23, 0x76, 0x42, 0xf1, 0x73, 0xec, 0x41,
	0x81, 0x19, 0x5d, 0x4c, 0xf7, 0x05, 0xe3, 0x25, 0x76, 0x23, 0xc4, 0xdd, 0x61, 0xf9, 0x61, 0x5a,
	0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x82, 0x89, 0x0c, 0x4c, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterBeacon defines a method to register a new beacon
	RegisterBeacon(ctx context.Context, in *MsgRegisterBeacon, opts ...grpc.CallOption) (*MsgRegisterBeaconResponse, error)
	// RecordBeaconTimestamp defines a method to record a timestamp for a registered beacon
	RecordBeaconTimestamp(ctx context.Context, in *MsgRecordBeaconTimestamp, opts ...grpc.CallOption) (*MsgRecordBeaconTimestampResponse, error)
	// PurchaseBeaconStateStorage defines the method to purchase more state storage
	PurchaseBeaconStateStorage(ctx context.Context, in *MsgPurchaseBeaconStateStorage, opts ...grpc.CallOption) (*MsgPurchaseBeaconStateStorageResponse, error)
	// UpdateParams defines an operation for updating the x/beacon module
	// parameters.
	// Since: cosmos-sdk 0.47
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterBeacon(ctx context.Context, in *MsgRegisterBeacon, opts ...grpc.CallOption) (*MsgRegisterBeaconResponse, error) {
	out := new(MsgRegisterBeaconResponse)
	err := c.cc.Invoke(ctx, "/mainchain.beacon.v1.Msg/RegisterBeacon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RecordBeaconTimestamp(ctx context.Context, in *MsgRecordBeaconTimestamp, opts ...grpc.CallOption) (*MsgRecordBeaconTimestampResponse, error) {
	out := new(MsgRecordBeaconTimestampResponse)
	err := c.cc.Invoke(ctx, "/mainchain.beacon.v1.Msg/RecordBeaconTimestamp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PurchaseBeaconStateStorage(ctx context.Context, in *MsgPurchaseBeaconStateStorage, opts ...grpc.CallOption) (*MsgPurchaseBeaconStateStorageResponse, error) {
	out := new(MsgPurchaseBeaconStateStorageResponse)
	err := c.cc.Invoke(ctx, "/mainchain.beacon.v1.Msg/PurchaseBeaconStateStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/mainchain.beacon.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterBeacon defines a method to register a new beacon
	RegisterBeacon(context.Context, *MsgRegisterBeacon) (*MsgRegisterBeaconResponse, error)
	// RecordBeaconTimestamp defines a method to record a timestamp for a registered beacon
	RecordBeaconTimestamp(context.Context, *MsgRecordBeaconTimestamp) (*MsgRecordBeaconTimestampResponse, error)
	// PurchaseBeaconStateStorage defines the method to purchase more state storage
	PurchaseBeaconStateStorage(context.Context, *MsgPurchaseBeaconStateStorage) (*MsgPurchaseBeaconStateStorageResponse, error)
	// UpdateParams defines an operation for updating the x/beacon module
	// parameters.
	// Since: cosmos-sdk 0.47
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterBeacon(ctx context.Context, req *MsgRegisterBeacon) (*MsgRegisterBeaconResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterBeacon not implemented")
}
func (*UnimplementedMsgServer) RecordBeaconTimestamp(ctx context.Context, req *MsgRecordBeaconTimestamp) (*MsgRecordBeaconTimestampResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordBeaconTimestamp not implemented")
}
func (*UnimplementedMsgServer) PurchaseBeaconStateStorage(ctx context.Context, req *MsgPurchaseBeaconStateStorage) (*MsgPurchaseBeaconStateStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurchaseBeaconStateStorage not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterBeacon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterBeacon)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterBeacon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mainchain.beacon.v1.Msg/RegisterBeacon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterBeacon(ctx, req.(*MsgRegisterBeacon))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RecordBeaconTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRecordBeaconTimestamp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RecordBeaconTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mainchain.beacon.v1.Msg/RecordBeaconTimestamp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RecordBeaconTimestamp(ctx, req.(*MsgRecordBeaconTimestamp))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PurchaseBeaconStateStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPurchaseBeaconStateStorage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PurchaseBeaconStateStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mainchain.beacon.v1.Msg/PurchaseBeaconStateStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PurchaseBeaconStateStorage(ctx, req.(*MsgPurchaseBeaconStateStorage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mainchain.beacon.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mainchain.beacon.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterBeacon",
			Handler:    _Msg_RegisterBeacon_Handler,
		},
		{
			MethodName: "RecordBeaconTimestamp",
			Handler:    _Msg_RecordBeaconTimestamp_Handler,
		},
		{
			MethodName: "PurchaseBeaconStateStorage",
			Handler:    _Msg_PurchaseBeaconStateStorage_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mainchain/beacon/v1/tx.proto",
}

func (m *MsgRegisterBeacon) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterBeacon) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterBeacon) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Moniker) > 0 {
		i -= len(m.Moniker)
		copy(dAtA[i:], m.Moniker)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Moniker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterBeaconResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterBeaconResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterBeaconResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BeaconId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BeaconId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgRecordBeaconTimestamp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRecordBeaconTimestamp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRecordBeaconTimestamp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x22
	}
	if m.SubmitTime != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SubmitTime))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x12
	}
	if m.BeaconId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BeaconId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgRecordBeaconTimestampResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRecordBeaconTimestampResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRecordBeaconTimestampResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimestampId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TimestampId))
		i--
		dAtA[i] = 0x10
	}
	if m.BeaconId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BeaconId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgPurchaseBeaconStateStorage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPurchaseBeaconStateStorage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPurchaseBeaconStateStorage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Number != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Number))
		i--
		dAtA[i] = 0x10
	}
	if m.BeaconId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BeaconId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgPurchaseBeaconStateStorageResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPurchaseBeaconStateStorageResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPurchaseBeaconStateStorageResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NumCanPurchase != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.NumCanPurchase))
		i--
		dAtA[i] = 0x18
	}
	if m.NumberPurchased != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.NumberPurchased))
		i--
		dAtA[i] = 0x10
	}
	if m.BeaconId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BeaconId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterBeacon) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Moniker)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterBeaconResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BeaconId != 0 {
		n += 1 + sovTx(uint64(m.BeaconId))
	}
	return n
}

func (m *MsgRecordBeaconTimestamp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BeaconId != 0 {
		n += 1 + sovTx(uint64(m.BeaconId))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.SubmitTime != 0 {
		n += 1 + sovTx(uint64(m.SubmitTime))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRecordBeaconTimestampResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BeaconId != 0 {
		n += 1 + sovTx(uint64(m.BeaconId))
	}
	if m.TimestampId != 0 {
		n += 1 + sovTx(uint64(m.TimestampId))
	}
	return n
}

func (m *MsgPurchaseBeaconStateStorage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BeaconId != 0 {
		n += 1 + sovTx(uint64(m.BeaconId))
	}
	if m.Number != 0 {
		n += 1 + sovTx(uint64(m.Number))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgPurchaseBeaconStateStorageResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BeaconId != 0 {
		n += 1 + sovTx(uint64(m.BeaconId))
	}
	if m.NumberPurchased != 0 {
		n += 1 + sovTx(uint64(m.NumberPurchased))
	}
	if m.NumCanPurchase != 0 {
		n += 1 + sovTx(uint64(m.NumCanPurchase))
	}
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterBeacon) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterBeacon: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterBeacon: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moniker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Moniker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterBeaconResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterBeaconResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterBeaconResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconId", wireType)
			}
			m.BeaconId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BeaconId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRecordBeaconTimestamp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRecordBeaconTimestamp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRecordBeaconTimestamp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconId", wireType)
			}
			m.BeaconId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BeaconId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmitTime", wireType)
			}
			m.SubmitTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubmitTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRecordBeaconTimestampResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRecordBeaconTimestampResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRecordBeaconTimestampResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconId", wireType)
			}
			m.BeaconId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BeaconId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampId", wireType)
			}
			m.TimestampId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimestampId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPurchaseBeaconStateStorage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPurchaseBeaconStateStorage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPurchaseBeaconStateStorage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconId", wireType)
			}
			m.BeaconId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BeaconId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Number", wireType)
			}
			m.Number = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Number |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPurchaseBeaconStateStorageResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPurchaseBeaconStateStorageResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPurchaseBeaconStateStorageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconId", wireType)
			}
			m.BeaconId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BeaconId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumberPurchased", wireType)
			}
			m.NumberPurchased = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumberPurchased |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumCanPurchase", wireType)
			}
			m.NumCanPurchase = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumCanPurchase |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
